services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ./api:/app
    command: "python manage.py runserver 0.0.0.0:${BACKEND_PORT}"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.frontend
      args:
        - VITE_APP_TITLE=${VITE_APP_TITLE:-App}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    env_file:
      - .env
    depends_on:
      - api

networks:
  default:
    name: dms_network
