services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    env_file:
      - .env
    volumes:
      - ./api:/app
    command: "python manage.py runserver 0.0.0.0:${BACKEND_PORT}"

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.frontend
      args:
        - VITE_APP_TITLE=${VITE_APP_TITLE:-App}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    env_file:
      - .env
    depends_on:
      - api
    volumes:
      - ./api/templates:/app/api/templates
      - ./api/documents:/app/api/documents

  vscode:
    image: codercom/code-server:latest
    ports:
      - "8443:8443"
    volumes:
      - ./api/templates:/home/coder/project/templates
      - ./api/documents:/home/coder/project/documents
      - ./vscode-config:/home/coder/.local/share/code-server
    environment:
      - CS_DISABLE_AUTH=true
    command: >
      sh -c "code-server --install-extension miragon-gmbh.miranum-json-forms && code-server --bind-addr 0.0.0.0:8443 /home/coder/project"

  editor:
    build:
      context: ./ui
      dockerfile: Dockerfile.editor
    ports:
      - "3000:80"
    volumes:
      - ./api/templates:/app/templates
      - ./api/documents:/app/documents

networks:
  default:
    name: dms_network
