# Generated by Django 6.0.3 on 2026-03-20 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("traveler", "Work Order Traveler"),
                            ("instructions", "Instructions"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_number", models.CharField(blank=True, max_length=100)),
                ("revision", models.CharField(blank=True, max_length=50)),
                ("serial_number", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instruction_details",
                        to="core.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InstructionStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("instruction_text", models.TextField()),
                (
                    "operator_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("operator_timestamp", models.DateTimeField(blank=True, null=True)),
                ("qa_name", models.CharField(blank=True, max_length=100, null=True)),
                ("qa_timestamp", models.DateTimeField(blank=True, null=True)),
                ("entry_values", models.JSONField(default=list)),
                (
                    "instruction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.instruction",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
        migrations.CreateModel(
            name="Traveler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_order", models.CharField(blank=True, max_length=100)),
                ("warehouse", models.CharField(blank=True, max_length=100)),
                ("part_number", models.CharField(blank=True, max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                ("serial_number", models.TextField(blank=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traveler_details",
                        to="core.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TravelerStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("label", models.CharField(max_length=100)),
                (
                    "operator_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("operator_timestamp", models.DateTimeField(blank=True, null=True)),
                ("qa_name", models.CharField(blank=True, max_length=100, null=True)),
                ("qa_timestamp", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("operation", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "traveler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.traveler",
                    ),
                ),
            ],
            options={
                "ordering": ["step_number"],
            },
        ),
    ]
