# Generated by Django 6.0.3 on 2026-03-21 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("rule", models.JSONField(help_text="FormCreate rules (JSON)")),
                (
                    "options",
                    models.JSONField(
                        blank=True, default=dict, help_text="FormCreate options (JSON)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="traveler",
            name="document",
        ),
        migrations.RemoveField(
            model_name="instruction",
            name="document",
        ),
        migrations.RemoveField(
            model_name="instructionstep",
            name="instruction",
        ),
        migrations.RemoveField(
            model_name="travelerstep",
            name="traveler",
        ),
        migrations.CreateModel(
            name="DocumentInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Form data (JSON)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="core.template",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.DeleteModel(
            name="Instruction",
        ),
        migrations.DeleteModel(
            name="InstructionStep",
        ),
        migrations.DeleteModel(
            name="Traveler",
        ),
        migrations.DeleteModel(
            name="TravelerStep",
        ),
    ]
