# Generated by Django 6.0.3 on 2026-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_documentinstance_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="options",
        ),
        migrations.RemoveField(
            model_name="template",
            name="rule",
        ),
        migrations.AddField(
            model_name="template",
            name="schema",
            field=models.JSONField(
                blank=True, default=dict, help_text="JSON Schema (data structure)"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="uischema",
            field=models.JSONField(
                blank=True, default=dict, help_text="UI Schema (layout)"
            ),
        ),
    ]
