# Generated by Django 6.0.3 on 2026-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_template_remove_traveler_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="template",
            name="is_active",
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Locked", "Locked"),
                    ("Archived", "Archived"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Archived", "Archived"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
